-- TASK: Find all reachable pages from 'home' whose names contain the substring ref or polic (case-sensitive)_
-- INSTRUCTIONS
-- 1. Write a recursive CTE paths (src,tgt) starting from 'home'
-- 2. In the final query, filter with a regex condition:
--      WHERE tgt ~*'(ref|polic)'.
-- 3. Return distinct reachable target page names.